<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ImageSorter.FileWrapper\ImageSorter.FileWrapper.csproj" />
      <ProjectReference Include="..\ImageSorter.Markdown.Abstractions\ImageSorter.Markdown.Abstractions.csproj" />
    </ItemGroup>

</Project>
