<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ImageParser.Utils\ImageParser.Utils.csproj" />
      <ProjectReference Include="..\ImageSorter.DateParsing.Abstractions\ImageSorter.DateParsing.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MetadataExtractor" Version="2.8.1" />
      <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.0" />
    </ItemGroup>

</Project>
